version: "3"
services:
  aigc-admin:
    image: dudulu/aigc-admin:beta-0320
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    command:
      - aigc-admin
      - start