version: "3"
services:
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      - MYSQL_DATABASE=aigc
      - MYSQL_USER=aigc
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin@123
      - TZ=Asia/Shanghai
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
    ]
    ports:
      - "3306:3306"
    volumes:
      - ./.cache/mysql:/var/lib/mysql
  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.cache/redis:/data
  aigc-admin:
    image: aigc-admin:0.0.0-pre-test
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command:
      - aigc-admin
      - start
    depends_on:
      - mysql
      - redis
  aigc-admin-cronjob:
    image: aigc-admin:0.0.0-pre-test
    restart: always
    build:
      dockerfile: Dockerfile
    command:
      - aigc-admin
      - cronjob
      - start
    depends_on:
      - mysql
      - redis