version: "3"
services:
  aigc-admin:
    image: dudulu/aigc-admin:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    command:
      - aigc-admin
      - start
  aigc-admin-cronjob:
    image: dudulu/aigc-admin:latest
    restart: always
    command:
      - aigc-admin
      - cronjob
      - start
    depends_on:
      - mysql
      - redis
  fschat-controller:
    image: dudulu/fschat:v0.2.36
    restart: always
    ports:
      - "21001:21001"
    command:
      - python3
      - -m
      - fastchat.serve.controller
      - --host
      - 0.0.0.0
      - --port
      - 21001
  fschat-api:
    image: dudulu/fschat:v0.2.36
    restart: always
    ports:
      - "8000:8000"
    command:
      - python3
      - -m
      - fastchat.serve.openai_api_server
      - --host
      - 0.0.0.0
      - --port
      - 8000
      - --controller-address
      - http://fschat-controller:21001